CREATE TABLE `accounts` (
  `id` int(10) ,
  `username` varchar(250) NOT NULL,
  `password` text NOT NULL
);
CREATE TABLE `products` (
  `id` int(10) NOT NULL,
  `nom` varchar(250) NOT NULL,
  `code` varchar(100) NOT NULL,
  `prix` double(9,2) NOT NULL,
  `image` varchar(250) NOT NULL
);
CREATE TABLE `categorie` (
  `id_cat` varchar(10) NOT NULL,
  `nom_cat` varchar(250) NOT NULL
);
CREATE TABLE `souscategorie` (
  `id_sous` int(10) NOT NULL,
  `nom_sous` varchar(250) NOT NULL,
  `cat` varchar(100) NOT NULL
);
--insert les produits dans la base de données
INSERT INTO `products` (`id`, `nom`, `code`, `prix`, `image`) VALUES
(1, 'For Bread Alone', 'Littérature / Romans', 140.00, 'ForBreadAlone.jpg'),
(2, 'Horses Of God', 'Littérature / Romans', 120.00, 'HorsesOfGod.jpg'),
(3, 'La Prisonniere', 'Littérature / Romans', 900.00, 'LaPrisonniere.jpg'),
(4, 'The Sand Child', 'Littérature / Romans', 68.00, 'TheSandChild.jpg'),
(5, 'La Boîte à merveilles', 'Littérature / Romans', 40.00, 'BoiteMerveilles.jpg'),
(6, "le dernier jour d'un condamné", 'Littérature / Romans', 35.00, 'LeDernierJour.jpg'),
(7, 'Miracle Morning', 'Dévelopement personnel', 110.00, 'MiracleMorning.jpg'),
(8, 'Tout Se Joue Avant 6 Ans', 'Parents / education', 100.00, 'ToutSeJoue.jpg'),
(9, 'Harry Potter', 'Littérature / Romans', 100.00, 'harryPotter.jpg'),
(10, "la psychologie de l'argent de morgan housel", 'Dévelopement personnel', 59.00, 'la-psychologie-de-l-argent-de-morgan-housel.jpg'),
(11, "ta deuxieme vie commence quand tu comprends que-tu n'en as", 'Dévelopement personnel', 125.00, 'raphaelle-giordano-ta-deuxieme-vie-commence-quand-tu-comprends-que-tu-n-en-as.jpg'),
(12, "influence et manipulation edition revue et augmentee robert cialdini", 'Dévelopement personnel', 110.00, '-influence-et-manipulation-edition-revue-et-augmentee-robert-cialdini.jpg'),
(13,"l'intelligence emotionnelle integrale", 'Dévelopement personnel', 100.00, 'l-intelligence-emotionnelle-integrale.jpg'),
(14, "laurent gounelle l'homme qui voulait etre heureux", 'Dévelopement personnel', 100.00, 'laurent-gounelle-l-homme-qui-voulait-etre-heureux.jpg'),
(15, "mortelle adele tome 7", 'Dévelopement personnel', 270.00, 'mortelle-adele-tome-7.jpg'),
(16, "comment se faire des amis dale carnegie", 'Dévelopement personnel', 320.00, 'comment-se-faire-des-amis-dale-carnegie.jpg'),
(17, "driss aberkane liberez votre cerveau", 'Dévelopement personnel', 100.00, 'driss-aberkane-liberez-votre-cerveau-.jpg'),
(18, "les hommes viennent de mars les femmes viennent de venus", 'Dévelopement personnel', 100.00, 'les-hommes-viennent-de-mars-les-femmes-viennent-de-venus-.jpg'),
(19, "le pouvoir du moment present guide d'eveil spirituel", 'Dévelopement personnel', 140.00, 'le-pouvoir-du-moment-present-guide-d-eveil-spirituel.jpg'),
(20, 'les 7 habitudes de ceux qui realisent tout ce qu-ils entreprennent le livre qui va changer votre vie', 'Dévelopement personnel', 136.00, '-les-7-habitudes-de-ceux-qui-realisent-tout-ce-qu-ils-entreprennent-le-livre-qui-va-changer-votre-vie-stephen-covey.jpg'),
(21, "trouver son pourquoi simon sinek", 'Dévelopement personnel', 140.00, 'trouver-son-pourquoi-simon-sinek.jpg'),
(22, "amazoncom l'autoroute du millionnaire la voie express vers la richesse mj demarco", 'Dévelopement personnel', 140.00, 'ForBreadAlone.jpg'),
(23, "l'art subtil de s'en foutre mark manson", 'Dévelopement personnel', 140.00, '-l-art-subtil-de-s-en-foutre-mark-manson.jpg'),
(24, "12 regles pour une vie un antidote au chaos poche jordan b peterson", 'DDévelopement personnel', 140.00, '-12-regles-pour-une-vie-un-antidote-au-chaos-poche-jordan-b-peterson-.jpg'),
(25, "d'une messiah by  frank herbert", 'Dévelopement personnel', 140.00, 'dune-messiah-by-frank-herbert.jpg'),
(26, "these violent lights by chloe gong", 'Dévelopement personnel', 140.00, 'these-violent-delights-by-chloe-gong.jpg'),
(27,'the power of now eckhart tolle','English books',200.00,'the-power-of-now-eckhart-tolle.jpg'),
(28,'courage is calling','English books',200.00,'courage-is-calling-by-ryan-holiday-.jpg'),
(29,'the 48 laws of power','English books',200.00,'the-48-laws-of-power-robert-greene.jpg'),
(30,'without merit colleen hoover','English books',200.00,'without-merit-colleen-hoover-.jpg'),
(31,'the practice by seth godin','English books',200.00,'the-practice-by-seth-godin.jpg'),
(32,'the unhoneymooners','English books',200.00,'the-unhoneymooners-by-christina-lauren.jpg'),
(33,'se faire obeir sans crier','Parents / education',22.00,'se-faire-obeir-sans-crier-jerry-wyckoff-barbara-unell.jpg'),
(34,'histoire a travers les costumes mon coffret montessori','Parents / education',22.00,'l-histoire-a-travers-les-costumes-mon-coffret-montessori-des-6-ans-de-sabine-hofmann.jpg'),
(35,'mortelle adeletome','Livres pour enfants',22.00,'mortelle-adele-tome-02-l-enfer-c-est-les-autres-format-kindle-de-miss-prickly-auteur.jpg'),
(36,'demon slayer t21','Mangas / BD',22.00,'demon-slayer-t21.jpg'),
(37,'one piece tome','Manga in english',22.00,'one-piece-tome-10-11-12-english.jpg'),
(38,'the lean startup','Entrepreneuriat / business',22.00,'the-lean-startup-eric-ries.jpg'),
(39,"cahier petit format 50 pages-","Cahier , carnet et bloc note",4.00,"cahier-petit-format-50-pages-.jpg"),
(40,"cahier petit format 100 pages","Cahier , carnet et bloc note",7.00,"cahier-petit-format-100-pages.jpg"),
(42,"cahier petit format 400 pages","Cahier , carnet et bloc note",25.00,"cahier-petit-format-400-pages-.jpg"),
(43,"carnet-100pages-de-dessin-blanche-a6-","Cahier , carnet et bloc note",12.00,"carnet-100pages-de-dessin-blanche-a6-.jpg"),
(44,"carnet-100pages-feuilles-blanches-a5-","Cahier , carnet et bloc note",54.00,"carnet-100pages-feuilles-blanches-a5-.jpg"),
(45,"feuilles-doubles-grand-format-blanche-100p-maped-","Feuille, copie et papier",35.00,"feuilles-doubles-grand-format-blanche-100p-maped-.jpg"),
(46,"agenda my hero academia","Agenda et cahier de texte",45.00,"agenda-my-hero-academia-2021-2022-de-kohei-horikoshi.jpg"),
(47,"classeure","Classement et protection",23.00,"classeure.jpg"),
(48,"stylo plume maped","ecriture et correction",25.00,"stylo-plume-maped-.jpg"),
(49,"stylo plume maped","ecriture et correction",15.50,"stylo-plume-maped-.jpg"),
(50,"fluo boss mini plusieurs couleurs","ecriture et correction",14.50,"fluo-boss-mini-plusieurs-couleurs.jpg"),
(51,"gomme legacy stabilo","ecriture et correction",5.00,"gomme-legacy-stabilo.jpg"),
(52,"pochette de 6 fluo staedtler","ecriture et correction",9.50,"pochette-de-6-fluo-staedtler.jpg"),
(53,"colle blanche 100ml faber castel","Colle, adhésif et pâte à fixe",9.00,"colle-blanche-100ml-faber-castel-.jpg"),
(54,"scotch grand format","Colle, adhésif et pâte à fixe",6.50,"scotch-grand-format.jpg"),
(55,"grande colle uhu stick-","Colle, adhésif et pâte à fixe",6.50,"grande-colle-uhu-stick-.jpg"),
(56,"ciseaux stainless maped","Ciseau",5.50,"ciseaux-stainless-maped-.jpg"),
(57,"ciseaux essentials de 17 cm","Ciseau",8.00,"ciseaux-essentials-de-17-cm-.jpg"),
(58,"regle flexible de 15 cm","Géométrie et traçage",10.00,"regle-flexible-de-15-cm.jpg"),
(59,"set de 3 pieces de geometrie maped","Géométrie et traçage",11.00,"set-de-3-pieces-de-geometrie-maped-.jpg"),
(60,"calculatrice scientifique deli-1710","Calculatrice",120.00,"calculatrice-scientifique-deli-1710.jpg"),
(61,"calculatrice scientifique casio-fx92","Calculatrice",80.00,"calculatrice-scientifique-casio-fx92.jpg"),
(62,"cartable sac a dos eastpak padded pak","Cartable",160.00,"cartable-sac-a-dos-eastpak-padded-pak-r.jpg"),
(63,"farby akrylowe studio acrylics 12 colours","Peinture acrylique",25.00,"farby-akrylowe-studio-acrylics-12-colours.jpg"),
(64,"studio acrylics 5-150 tubes","Peinture acrylique",13.00,"studio-acrylics-5-150-tubes.jpg"),
(65,"pebeo studio huile xl","Peinture à l'huile",14.50,"pebeo-studio-huile-xl-.jpg"),
(66,"faber castell pitt 1pices noir fusain fusains noir noir 1 pices","Peinture divers",8.00,"faber-castell-pitt-1pices-noir-fusain-fusains-noir-noir-1-pices.jpg"),
(67,"faber castell 112976 stylo bille noir","Peinture divers",11.00,"faber-castell-112976-stylo-bille-noir-noir.jpg");



INSERT INTO `categorie` (`id_cat`, `nom_cat`) VALUES
('59', 'LIVRES'),
('60', 'FOURNITURES SCOLAIRES'),
('61', 'BEAUX-ARTS/ DESSIN')
;


INSERT INTO `souscategorie` (`id_sous`, `nom_sous`,`cat`) VALUES
(1, 'Dévelopement personnel','LIVRES'),
(2, 'Littérature / Romans','LIVRES'),
(3, 'English books','LIVRES'),
(4, 'Parents / education','LIVRES'),
(5, 'La pédagogie Montessori','LIVRES'),
(6, 'Livres pour enfants','LIVRES'),
(7, 'Mangas / BD','LIVRES'),
(8, 'Manga in english','LIVRES'),
(9, 'Entrepreneuriat / business','LIVRES'),
(10,'افضل الكتب العربية','LIVRES'),
(11,'Beaux livres','LIVRES'),
(12,'Couple, séduction et relation','LIVRES'),
(13,'Petite section','LIVRES'),
(14,'Moyenne section','LIVRES'),
(15,'Grande section','LIVRES'),
(16,'CP / CE1','LIVRES'),
(17,'CE1 / CE2','LIVRES'),
(18,'CE2 / CE3','LIVRES'),
(19,'CM1 / CE4','LIVRES'),
(20,'CM2 / CE5','LIVRES'),
(21,'6éme / CE6','LIVRES'),
(22,'5émé / 1ére année collège','LIVRES'),
(23,'4émé / 2éme année collège','LIVRES'),
(24,'3émé / 3éme année collège','LIVRES'),
(25,'2de / Tronc commun','LIVRES'),
(26,'1ére / 1ére année BAC','LIVRES'),
(27,'Terminal / 2éme année BAC','LIVRES'),
(28,'Dictionnaire et conjugaison', 'LIVRES'),
(29,'Annals / Exercices corrigés','LIVRES'),
(30,'Livres de vacances', 'LIVRES'),
(31,'Livres de médecine','LIVRES'),
(32,'Cahier , carnet et bloc note', 'FOURNITURES SCOLAIRES'),
(33,'Feuille, copie et papier','FOURNITURES SCOLAIRES'),
(34,'Agenda et cahier de texte','FOURNITURES SCOLAIRES'),
(35,'Classement et protection','FOURNITURES SCOLAIRES'),
(36,'ecriture et correction', 'FOURNITURES SCOLAIRES'),
(37,'Colle, adhésif et pâte à fixe','FOURNITURES SCOLAIRES'),
(38,'Ciseau','FOURNITURES SCOLAIRES'),
(39,'Géométrie et traçage', 'FOURNITURES SCOLAIRES'),
(40,'Dessin, musique et peinture','FOURNITURES SCOLAIRES'),
(41,'Calculatrice', 'FOURNITURES SCOLAIRES'),
(43,'Cartable', 'FOURNITURES SCOLAIRES'),
(44,"Trousse",'FOURNITURES SCOLAIRES'),
(45,"sac à gouter", 'FOURNITURES SCOLAIRES'),
(46,"Sacs banane et bandouliére", 'FOURNITURES SCOLAIRES'),
(47,'Peinture acrylique','BEAUX-ARTS/ DESSIN'),
(48,"Peinture à l'huile",'BEAUX-ARTS/ DESSIN'),
(49,"Peinture divers",'BEAUX-ARTS/ DESSIN'),
(50,'Pinceaux-Brosses','BEAUX-ARTS/ DESSIN'),
(51,'Spray', 'BEAUX-ARTS/ DESSIN'),
(52,'Crayons et fusais','BEAUX-ARTS/ DESSIN'),
(53,'Feutres et marqueurs','BEAUX-ARTS/ DESSIN'),
(54,'Pastels', 'BEAUX-ARTS/ DESSIN'),
(55,'Toile et chevalet','BEAUX-ARTS/ DESSIN'),
(56,'Bloc de dessin / papier','BEAUX-ARTS/ DESSIN'),
(57,'Accessoires-divers','BEAUX-ARTS/ DESSIN'),
(58,'BEST SELLERS','BEST SELLERS');

